"""empty message

Revision ID: 06416e53452a
Revises: fd5b12e9aa87
Create Date: 2025-06-23 09:36:16.166778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06416e53452a'
down_revision = 'fd5b12e9aa87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ranking_user',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ranking_user',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
