"""empty message

Revision ID: 6f82a16b49fa
Revises: 0763d677d453
Create Date: 2025-06-06 11:06:52.428014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f82a16b49fa'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('dificultad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('respuestas_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.ForeignKeyConstraint(['respuestas_user'], ['respuestas_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ranking_user', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('experiencia', sa.Integer(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('experiencia')
        batch_op.drop_column('avatar')
        batch_op.drop_column('ranking_user')
        batch_op.drop_column('user_name')

    op.drop_table('partida')
    op.drop_table('respuestas_user')
    op.drop_table('preguntas')
    op.drop_table('categoria')
    # ### end Alembic commands ###
