"""empty message

Revision ID: a6654e5451db
Revises: 0763d677d453
Create Date: 2025-05-31 12:02:43.945723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6654e5451db'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ranking_user', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('experiencia', sa.Integer(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('experiencia')
        batch_op.drop_column('avatar')
        batch_op.drop_column('ranking_user')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
